server:
  port: 8770
spring:
  application:
    name: storage-service
  security:
    user:
      name: admin
      password: 1234554321
  servlet:
    multipart:
      max-file-size: 10mb
      max-request-size: 20mb
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/article?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456*
    driver-class-name: com.mysql.jdbc.Driver
eureka:
  instance:
    hostname: localhost:8761
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
  client:
    serviceUrl:
        defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}/eureka/
security:
  oauth2:
    client:
      access-token-uri: http://article.yrclubs.com/sso/oauth/token
      user-authorization-uri: http://article.yrclubs.com/sso/oauth/authorize
      grant-type: article-client
      client-secret: article-secret
    resource:
      user-info-uri: http://article.yrclubs.com/sso/user
      prefer-token-info: false
